package vault

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

// IndexStats summarizes an index.md generation pass.
type IndexStats struct {
	Folders int // folders whose index.md was (re)generated
	Written int // index.md files that actually changed on disk
}

// GenerateIndexes (re)writes a per-folder `index.md` catalog (slug → description)
// for every top-level content folder, plus a root `index.md` linking them.
// Writes are idempotent: a file is only rewritten when its content changes.
func GenerateIndexes(root string) (IndexStats, error) {
	var st IndexStats

	files, err := WalkPages(root)
	if err != nil {
		return st, err
	}

	byFolder := map[string][]*Page{}
	for _, abs := range files {
		p, err := ParsePage(abs, root)
		if err != nil {
			continue
		}
		if p.Folder == "" {
			continue // root-level notes (CLAUDE.md, working.md) aren't catalogued here
		}
		byFolder[p.Folder] = append(byFolder[p.Folder], p)
	}

	folders := make([]string, 0, len(byFolder))
	for folder := range byFolder {
		folders = append(folders, folder)
	}
	sort.Strings(folders)

	for _, folder := range folders {
		pages := byFolder[folder]
		sort.Slice(pages, func(i, j int) bool { return pages[i].Slug < pages[j].Slug })
		content := renderFolderIndex(folder, pages)
		wrote, err := writeIfChanged(filepath.Join(root, folder, "index.md"), content)
		if err != nil {
			return st, err
		}
		st.Folders++
		if wrote {
			st.Written++
		}
	}

	rootContent := renderRootIndex(folders, byFolder)
	wrote, err := writeIfChanged(filepath.Join(root, "index.md"), rootContent)
	if err != nil {
		return st, err
	}
	if wrote {
		st.Written++
	}

	return st, nil
}

func renderFolderIndex(folder string, pages []*Page) string {
	var sb strings.Builder
	fmt.Fprintf(&sb, "# Index — %s\n\n", folder)
	fmt.Fprintf(&sb, "_%d page(s). Auto-generated by mnemo from each page's `description:`. Do not edit by hand._\n\n", len(pages))
	sb.WriteString("| Slug | Description | Tags |\n")
	sb.WriteString("|------|-------------|------|\n")
	for _, p := range pages {
		fmt.Fprintf(&sb, "| [[%s]] | %s | %s |\n",
			p.Slug, cell(p.Description), cell(strings.Join(p.Tags, ", ")))
	}
	return sb.String()
}

func renderRootIndex(folders []string, byFolder map[string][]*Page) string {
	var sb strings.Builder
	sb.WriteString("# Vault index\n\n")
	sb.WriteString("_Auto-generated by mnemo. Each folder has its own `index.md` catalog._\n\n")
	sb.WriteString("| Folder | Pages |\n")
	sb.WriteString("|--------|-------|\n")
	for _, f := range folders {
		fmt.Fprintf(&sb, "| [%s](%s/index.md) | %d |\n", f, f, len(byFolder[f]))
	}
	return sb.String()
}

var refSlugRE = regexp.MustCompile(`\[\[([^\]|#]+)`)

// ReferencedSlugs returns the set of slugs wikilinked from the file at path
// (e.g. the CLAUDE.md hot cache). Missing file → empty set.
func ReferencedSlugs(path string) map[string]bool {
	out := map[string]bool{}
	data, err := os.ReadFile(path)
	if err != nil {
		return out
	}
	for _, m := range refSlugRE.FindAllStringSubmatch(string(data), -1) {
		out[strings.TrimSpace(m[1])] = true
	}
	return out
}

// cell escapes a value for safe inclusion in a markdown table cell.
func cell(s string) string {
	s = strings.ReplaceAll(s, "\n", " ")
	s = strings.ReplaceAll(s, "|", "\\|")
	if s == "" {
		return "—"
	}
	return s
}

// writeIfChanged writes content to path only when it differs from what's there.
func writeIfChanged(path, content string) (bool, error) {
	if existing, err := os.ReadFile(path); err == nil && string(existing) == content {
		return false, nil
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return false, err
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return false, err
	}
	return true, nil
}
